### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by xRahul** [rohitjain00/Musical_Gloves#1]
Hi,

If possible, please add an Install / getting started note in the readme stating which softwares to install using what commands and how to load this code into the arduino. It is not clear by the readme.

Also, what are the contents of keypad.zip? If possible, can you add that without the zip? It is easier to browse through the files if they are unzipped.

**Comment by rohitjain00** [comment]
I've added a get started reference link. You should visit the link to get information about software installation.
Keypad.zip is the library for using keypad with arduino I've attached it for the ease. You could visit the below link to browse files in Keypad.zip
(https://github.com/Chris--A/Keypad)

**Comment by xRahul** [comment]
Instead of adding it as zip, you can add it as a s.ubmodule. Ref: https://github.com/blog/2104-working-with-submodules
